const ALLOWED_UPLOAD_FORMATS = ["PNG", "JPG", "PDF", "AI", "PSD", "FIGMA", "MP4", "GIF"];

const SERVICE_CATEGORIES = [
  {
    id: "branding",
    title: "Branding",
    description: "Core brand identity and visual systems for businesses and products.",
  },
  {
    id: "social_media",
    title: "Social Media",
    description: "Creative assets tailored for social media campaigns and growth.",
  },
  {
    id: "marketing_materials",
    title: "Marketing Materials",
    description: "Sales and promotional collateral for digital and print channels.",
  },
  {
    id: "outdoor_print",
    title: "Outdoor Print",
    description: "Large-format and physical advertising assets for public spaces.",
  },
  {
    id: "events",
    title: "Events",
    description: "Visual assets for conferences, activations, and event experiences.",
  },
  {
    id: "digital_marketing",
    title: "Digital Marketing",
    description: "Performance-focused digital creatives for web and paid channels.",
  },
  {
    id: "merchandise",
    title: "Merchandise",
    description: "Branded merchandise designs for distribution and retail.",
  },
  {
    id: "packaging",
    title: "Packaging",
    description: "Product packaging and label systems for consumer goods.",
  },
];

const DESIGN_DELIVERABLES = [
  // Branding
  {
    id: "logo_design",
    title: "Logo Design",
    category: "branding",
    description: "Original logo concept development with presentation mockups.",
    typicalCredits: 8,
    internalWorkloadScore: 13,
    complexity: "high",
    dimensions: ["Vector", "Horizontal", "Square"],
    allowedFormats: ["PNG", "JPG", "PDF", "AI"],
    requiredSkills: ["branding", "logo_design", "vector_illustration"],
  },
  {
    id: "logo_redesign",
    title: "Logo Redesign",
    category: "branding",
    description: "Modernization and refinement of an existing logo system.",
    typicalCredits: 6,
    internalWorkloadScore: 10,
    complexity: "high",
    dimensions: ["Vector", "Horizontal", "Square"],
    allowedFormats: ["PNG", "JPG", "PDF", "AI"],
    requiredSkills: ["branding", "logo_design", "brand_strategy"],
  },
  {
    id: "brand_guidelines",
    title: "Brand Guidelines",
    category: "branding",
    description: "Brand rules document covering typography, colors, and usage.",
    typicalCredits: 6,
    internalWorkloadScore: 11,
    complexity: "high",
    dimensions: ["A4", "US Letter", "Digital PDF"],
    allowedFormats: ["PDF", "FIGMA"],
    requiredSkills: ["branding", "layout_design", "documentation"],
  },
  {
    id: "brand_identity_kit",
    title: "Brand Identity Kit",
    category: "branding",
    description: "Starter brand package with core assets and applications.",
    typicalCredits: 7,
    internalWorkloadScore: 12,
    complexity: "high",
    dimensions: ["Mixed"],
    allowedFormats: ["PNG", "JPG", "PDF", "AI", "FIGMA"],
    requiredSkills: ["branding", "logo_design", "brand_systems"],
  },
  {
    id: "color_palette_design",
    title: "Color Palette Design",
    category: "branding",
    description: "Strategic color palette aligned to brand positioning.",
    typicalCredits: 3,
    internalWorkloadScore: 5,
    complexity: "medium",
    dimensions: ["Digital swatches"],
    allowedFormats: ["PDF", "PNG", "FIGMA"],
    requiredSkills: ["branding", "color_theory"],
  },

  // Social media
  {
    id: "instagram_post",
    title: "Instagram Post",
    category: "social_media",
    description: "Single-feed creative optimized for engagement.",
    typicalCredits: 1,
    internalWorkloadScore: 2,
    complexity: "low",
    dimensions: ["1080x1080"],
    allowedFormats: ["PNG", "JPG", "GIF"],
    requiredSkills: ["social_media_design", "layout_design"],
  },
  {
    id: "instagram_carousel",
    title: "Instagram Carousel",
    category: "social_media",
    description: "Multi-slide narrative carousel for Instagram.",
    typicalCredits: 2,
    internalWorkloadScore: 4,
    complexity: "medium",
    dimensions: ["1080x1080"],
    allowedFormats: ["PNG", "JPG", "PDF"],
    requiredSkills: ["social_media_design", "storytelling"],
  },
  {
    id: "instagram_story",
    title: "Instagram Story",
    category: "social_media",
    description: "Vertical story creative for campaigns and announcements.",
    typicalCredits: 1,
    internalWorkloadScore: 2,
    complexity: "low",
    dimensions: ["1080x1920"],
    allowedFormats: ["PNG", "JPG", "GIF", "MP4"],
    requiredSkills: ["social_media_design", "motion_basics"],
  },
  {
    id: "facebook_post",
    title: "Facebook Post",
    category: "social_media",
    description: "Feed post optimized for Facebook audiences.",
    typicalCredits: 1,
    internalWorkloadScore: 2,
    complexity: "low",
    dimensions: ["1200x630"],
    allowedFormats: ["PNG", "JPG", "GIF"],
    requiredSkills: ["social_media_design"],
  },
  {
    id: "linkedin_post",
    title: "LinkedIn Post",
    category: "social_media",
    description: "Professional social post for B2B communication.",
    typicalCredits: 1,
    internalWorkloadScore: 2,
    complexity: "low",
    dimensions: ["1200x1200"],
    allowedFormats: ["PNG", "JPG"],
    requiredSkills: ["social_media_design", "corporate_design"],
  },
  {
    id: "twitter_x_graphic",
    title: "Twitter/X Graphic",
    category: "social_media",
    description: "Feed creative optimized for X timelines.",
    typicalCredits: 1,
    internalWorkloadScore: 2,
    complexity: "low",
    dimensions: ["1600x900"],
    allowedFormats: ["PNG", "JPG", "GIF"],
    requiredSkills: ["social_media_design"],
  },
  {
    id: "youtube_thumbnail",
    title: "YouTube Thumbnail",
    category: "social_media",
    description: "Click-optimized thumbnail for video content.",
    typicalCredits: 1,
    internalWorkloadScore: 3,
    complexity: "medium",
    dimensions: ["1280x720"],
    allowedFormats: ["PNG", "JPG"],
    requiredSkills: ["thumbnail_design", "photo_editing"],
  },
  {
    id: "youtube_channel_art",
    title: "YouTube Channel Art",
    category: "social_media",
    description: "Branded channel banner for YouTube pages.",
    typicalCredits: 2,
    internalWorkloadScore: 4,
    complexity: "medium",
    dimensions: ["2560x1440"],
    allowedFormats: ["PNG", "JPG", "FIGMA"],
    requiredSkills: ["banner_design", "branding"],
  },

  // Marketing materials
  {
    id: "flyer_design",
    title: "Flyer Design",
    category: "marketing_materials",
    description: "Single-page flyer for promotion and outreach.",
    typicalCredits: 2,
    internalWorkloadScore: 4,
    complexity: "medium",
    dimensions: ["A5", "A4"],
    allowedFormats: ["PDF", "PNG", "JPG", "AI"],
    requiredSkills: ["print_design", "layout_design"],
  },
  {
    id: "poster_design",
    title: "Poster Design",
    category: "marketing_materials",
    description: "Promotional poster for digital and print visibility.",
    typicalCredits: 2,
    internalWorkloadScore: 4,
    complexity: "medium",
    dimensions: ["A3", "A2"],
    allowedFormats: ["PDF", "PNG", "JPG", "AI"],
    requiredSkills: ["print_design", "layout_design"],
  },
  {
    id: "brochure_design",
    title: "Brochure Design",
    category: "marketing_materials",
    description: "Multi-panel or booklet brochure for products/services.",
    typicalCredits: 4,
    internalWorkloadScore: 8,
    complexity: "high",
    dimensions: ["A4", "Tri-fold"],
    allowedFormats: ["PDF", "AI", "FIGMA"],
    requiredSkills: ["print_design", "layout_design", "editorial_design"],
  },
  {
    id: "company_profile",
    title: "Company Profile",
    category: "marketing_materials",
    description: "Corporate profile deck or booklet for business presentation.",
    typicalCredits: 4,
    internalWorkloadScore: 8,
    complexity: "high",
    dimensions: ["A4", "16:9"],
    allowedFormats: ["PDF", "FIGMA"],
    requiredSkills: ["editorial_design", "corporate_design"],
  },
  {
    id: "catalog_design",
    title: "Catalog Design",
    category: "marketing_materials",
    description: "Structured product or service catalog layout.",
    typicalCredits: 5,
    internalWorkloadScore: 9,
    complexity: "high",
    dimensions: ["A4", "Square"],
    allowedFormats: ["PDF", "AI", "FIGMA"],
    requiredSkills: ["editorial_design", "layout_design"],
  },
  {
    id: "menu_design",
    title: "Menu Design",
    category: "marketing_materials",
    description: "Restaurant or hospitality menu with clear hierarchy.",
    typicalCredits: 3,
    internalWorkloadScore: 5,
    complexity: "medium",
    dimensions: ["A4", "A3", "DL"],
    allowedFormats: ["PDF", "PNG", "AI"],
    requiredSkills: ["print_design", "typography"],
  },
  {
    id: "product_sheet",
    title: "Product Sheet",
    category: "marketing_materials",
    description: "Single-page product information and feature sheet.",
    typicalCredits: 2,
    internalWorkloadScore: 4,
    complexity: "medium",
    dimensions: ["A4"],
    allowedFormats: ["PDF", "PNG", "FIGMA"],
    requiredSkills: ["layout_design", "information_design"],
  },

  // Outdoor advertising
  {
    id: "billboard_design",
    title: "Billboard Design",
    category: "outdoor_print",
    description: "Large-format billboard creative for high-visibility campaigns.",
    typicalCredits: 4,
    internalWorkloadScore: 8,
    complexity: "high",
    dimensions: ["6x3 m", "12x3 m"],
    allowedFormats: ["PDF", "AI", "PNG"],
    requiredSkills: ["outdoor_advertising", "layout_design"],
  },
  {
    id: "roll_up_banner",
    title: "Roll-up Banner",
    category: "outdoor_print",
    description: "Portable event banner for indoor and outdoor activations.",
    typicalCredits: 3,
    internalWorkloadScore: 5,
    complexity: "medium",
    dimensions: ["85x200 cm"],
    allowedFormats: ["PDF", "AI", "PNG"],
    requiredSkills: ["print_design", "outdoor_advertising"],
  },
  {
    id: "pull_up_banner",
    title: "Pull-up Banner",
    category: "outdoor_print",
    description: "Branded pull-up stand design for promotions and expos.",
    typicalCredits: 3,
    internalWorkloadScore: 5,
    complexity: "medium",
    dimensions: ["85x200 cm"],
    allowedFormats: ["PDF", "AI", "PNG"],
    requiredSkills: ["print_design", "outdoor_advertising"],
  },
  {
    id: "street_banner",
    title: "Street Banner",
    category: "outdoor_print",
    description: "Street-level banner for road and city placement.",
    typicalCredits: 3,
    internalWorkloadScore: 6,
    complexity: "medium",
    dimensions: ["100x300 cm"],
    allowedFormats: ["PDF", "AI", "PNG"],
    requiredSkills: ["outdoor_advertising", "print_design"],
  },
  {
    id: "shop_signage",
    title: "Shop Signage",
    category: "outdoor_print",
    description: "Signage creative for storefront visibility.",
    typicalCredits: 3,
    internalWorkloadScore: 6,
    complexity: "medium",
    dimensions: ["Custom"],
    allowedFormats: ["PDF", "AI", "PNG"],
    requiredSkills: ["signage_design", "branding"],
  },
  {
    id: "lightbox_signage",
    title: "Lightbox Signage",
    category: "outdoor_print",
    description: "Backlit signage layout for high-impact branding.",
    typicalCredits: 4,
    internalWorkloadScore: 7,
    complexity: "high",
    dimensions: ["Custom"],
    allowedFormats: ["PDF", "AI", "PNG"],
    requiredSkills: ["signage_design", "print_production"],
  },

  // Event materials
  {
    id: "event_poster",
    title: "Event Poster",
    category: "events",
    description: "Poster design for event awareness and attendance.",
    typicalCredits: 2,
    internalWorkloadScore: 4,
    complexity: "medium",
    dimensions: ["A3", "A2"],
    allowedFormats: ["PDF", "PNG", "JPG", "AI"],
    requiredSkills: ["event_design", "print_design"],
  },
  {
    id: "event_banner",
    title: "Event Banner",
    category: "events",
    description: "Event-specific banner for onsite branding.",
    typicalCredits: 3,
    internalWorkloadScore: 5,
    complexity: "medium",
    dimensions: ["Custom"],
    allowedFormats: ["PDF", "AI", "PNG"],
    requiredSkills: ["event_design", "print_design"],
  },
  {
    id: "event_invitation",
    title: "Event Invitation",
    category: "events",
    description: "Digital or print invitation assets for event guests.",
    typicalCredits: 2,
    internalWorkloadScore: 3,
    complexity: "low",
    dimensions: ["1080x1080", "A6"],
    allowedFormats: ["PNG", "JPG", "PDF"],
    requiredSkills: ["event_design", "social_media_design"],
  },
  {
    id: "event_ticket",
    title: "Event Ticket",
    category: "events",
    description: "Ticket layout for entry management and branding.",
    typicalCredits: 2,
    internalWorkloadScore: 3,
    complexity: "low",
    dimensions: ["DL", "Custom"],
    allowedFormats: ["PDF", "PNG", "AI"],
    requiredSkills: ["event_design", "print_design"],
  },
  {
    id: "stage_backdrop",
    title: "Stage Backdrop",
    category: "events",
    description: "Large backdrop design for conference or concert stage.",
    typicalCredits: 4,
    internalWorkloadScore: 8,
    complexity: "high",
    dimensions: ["Custom large format"],
    allowedFormats: ["PDF", "AI", "PNG"],
    requiredSkills: ["event_design", "outdoor_advertising"],
  },
  {
    id: "conference_signage",
    title: "Conference Signage",
    category: "events",
    description: "Directional and informational signage suite for conferences.",
    typicalCredits: 4,
    internalWorkloadScore: 7,
    complexity: "high",
    dimensions: ["Mixed signage set"],
    allowedFormats: ["PDF", "AI", "PNG"],
    requiredSkills: ["event_design", "information_design"],
  },

  // Merchandise
  {
    id: "tshirt_design",
    title: "T-shirt Design",
    category: "merchandise",
    description: "Artwork placement and composition for t-shirt printing.",
    typicalCredits: 2,
    internalWorkloadScore: 4,
    complexity: "medium",
    dimensions: ["Vector", "4500x5400"],
    allowedFormats: ["PNG", "PDF", "AI", "PSD"],
    requiredSkills: ["merch_design", "illustration"],
  },
  {
    id: "cap_design",
    title: "Cap Design",
    category: "merchandise",
    description: "Cap artwork optimized for embroidery or print.",
    typicalCredits: 2,
    internalWorkloadScore: 3,
    complexity: "low",
    dimensions: ["Vector"],
    allowedFormats: ["PNG", "PDF", "AI"],
    requiredSkills: ["merch_design", "branding"],
  },
  {
    id: "sticker_design",
    title: "Sticker Design",
    category: "merchandise",
    description: "Sticker artwork for promotional or retail use.",
    typicalCredits: 1,
    internalWorkloadScore: 2,
    complexity: "low",
    dimensions: ["Custom"],
    allowedFormats: ["PNG", "JPG", "PDF", "AI"],
    requiredSkills: ["illustration", "print_design"],
  },
  {
    id: "tote_bag_design",
    title: "Tote Bag Design",
    category: "merchandise",
    description: "Print-ready artwork for tote bags and accessories.",
    typicalCredits: 2,
    internalWorkloadScore: 3,
    complexity: "low",
    dimensions: ["Vector"],
    allowedFormats: ["PNG", "PDF", "AI"],
    requiredSkills: ["merch_design", "illustration"],
  },
  {
    id: "mug_design",
    title: "Mug Design",
    category: "merchandise",
    description: "Wrap-around mug artwork for branded merchandise.",
    typicalCredits: 2,
    internalWorkloadScore: 3,
    complexity: "low",
    dimensions: ["8.75x3.75 in"],
    allowedFormats: ["PNG", "PDF", "AI"],
    requiredSkills: ["merch_design", "layout_design"],
  },
  {
    id: "notebook_cover",
    title: "Notebook Cover",
    category: "merchandise",
    description: "Cover artwork for journals and notebook products.",
    typicalCredits: 2,
    internalWorkloadScore: 3,
    complexity: "low",
    dimensions: ["A5", "B5"],
    allowedFormats: ["PNG", "PDF", "AI"],
    requiredSkills: ["print_design", "layout_design"],
  },

  // Digital marketing
  {
    id: "website_hero_banner",
    title: "Website Hero Banner",
    category: "digital_marketing",
    description: "Hero section visual for website landing experiences.",
    typicalCredits: 2,
    internalWorkloadScore: 4,
    complexity: "medium",
    dimensions: ["1920x1080", "1440x900"],
    allowedFormats: ["PNG", "JPG", "FIGMA"],
    requiredSkills: ["web_design", "digital_marketing"],
  },
  {
    id: "landing_page_graphics",
    title: "Landing Page Graphics",
    category: "digital_marketing",
    description: "Visual asset set for conversion-focused landing pages.",
    typicalCredits: 3,
    internalWorkloadScore: 6,
    complexity: "medium",
    dimensions: ["Responsive set"],
    allowedFormats: ["PNG", "JPG", "FIGMA", "GIF"],
    requiredSkills: ["web_design", "digital_marketing", "ui_design"],
  },
  {
    id: "email_newsletter_design",
    title: "Email Newsletter Design",
    category: "digital_marketing",
    description: "Template-ready newsletter layout and visuals.",
    typicalCredits: 3,
    internalWorkloadScore: 5,
    complexity: "medium",
    dimensions: ["600px width"],
    allowedFormats: ["PNG", "JPG", "FIGMA", "PDF"],
    requiredSkills: ["email_design", "layout_design"],
  },
  {
    id: "blog_featured_images",
    title: "Blog Featured Images",
    category: "digital_marketing",
    description: "Set of featured images for editorial content.",
    typicalCredits: 2,
    internalWorkloadScore: 3,
    complexity: "low",
    dimensions: ["1200x628"],
    allowedFormats: ["PNG", "JPG", "GIF"],
    requiredSkills: ["digital_marketing", "social_media_design"],
  },
  {
    id: "google_display_ads",
    title: "Google Display Ads",
    category: "digital_marketing",
    description: "Multi-size display ad creatives for campaign deployment.",
    typicalCredits: 3,
    internalWorkloadScore: 6,
    complexity: "medium",
    dimensions: ["300x250", "728x90", "160x600"],
    allowedFormats: ["PNG", "JPG", "GIF", "MP4"],
    requiredSkills: ["digital_marketing", "ad_design"],
  },

  // Packaging
  {
    id: "product_packaging",
    title: "Product Packaging",
    category: "packaging",
    description: "Primary packaging system for retail products.",
    typicalCredits: 5,
    internalWorkloadScore: 10,
    complexity: "high",
    dimensions: ["Custom dieline"],
    allowedFormats: ["PDF", "AI", "PSD", "PNG"],
    requiredSkills: ["packaging_design", "print_production"],
  },
  {
    id: "box_packaging",
    title: "Box Packaging",
    category: "packaging",
    description: "Box wrap and panel designs aligned to brand standards.",
    typicalCredits: 5,
    internalWorkloadScore: 10,
    complexity: "high",
    dimensions: ["Custom dieline"],
    allowedFormats: ["PDF", "AI", "PSD"],
    requiredSkills: ["packaging_design", "dieline_handling"],
  },
  {
    id: "bottle_label",
    title: "Bottle Label",
    category: "packaging",
    description: "Label system for beverages and liquid products.",
    typicalCredits: 4,
    internalWorkloadScore: 7,
    complexity: "medium",
    dimensions: ["Custom label"],
    allowedFormats: ["PDF", "AI", "PNG"],
    requiredSkills: ["packaging_design", "label_design"],
  },
  {
    id: "food_packaging",
    title: "Food Packaging",
    category: "packaging",
    description: "Regulation-aware food packaging creative.",
    typicalCredits: 5,
    internalWorkloadScore: 10,
    complexity: "high",
    dimensions: ["Custom dieline"],
    allowedFormats: ["PDF", "AI", "PSD"],
    requiredSkills: ["packaging_design", "food_branding"],
  },
  {
    id: "cosmetic_packaging",
    title: "Cosmetic Packaging",
    category: "packaging",
    description: "Premium cosmetic packaging and label visuals.",
    typicalCredits: 5,
    internalWorkloadScore: 10,
    complexity: "high",
    dimensions: ["Custom dieline"],
    allowedFormats: ["PDF", "AI", "PSD"],
    requiredSkills: ["packaging_design", "beauty_branding"],
  },
];

module.exports = {
  ALLOWED_UPLOAD_FORMATS,
  SERVICE_CATEGORIES,
  DESIGN_DELIVERABLES,
};
